var appRoutes = express.Router(); 
var contestReports = require('../../controller/reports/contestReports');

appRoutes.post('/contest',  contestReports.contestReport);
appRoutes.post('/contestsummary',  contestReports.contestSummaryReport);
appRoutes.post('/registered',contestReports.registered);
appRoutes.post('/userAcquisitionSummary',contestReports.userAcquisitionSummary);
appRoutes.post('/channelacquisitionsummary',contestReports.channelAcquisitionSummary);
appRoutes.post('/userAcquisitionDetail',contestReports.userAcquisitionDetail);
appRoutes.post('/Summary',contestReports.summary);
appRoutes.post('/dailysummary',contestReports.dailySummary);
appRoutes.post('/dailychannelwisesummary',contestReports.dailyChannelWiseSummary);
appRoutes.post('/dashboard',contestReports.dashboardReport);
appRoutes.post('/userfunnelsummary',contestReports.userFunnelSummary);
appRoutes.post('/downloadsummary',contestReports.downloadSummary);
appRoutes.post('/cashreport',contestReports.cashReport);
appRoutes.post('/paymentgatewayreport',contestReports.paymentgatewayReport);
appRoutes.post('/paymentgatewaydetailreport',contestReports.paymentgatewayDetailReport);
appRoutes.post('/topgamesummary',contestReports.topGameSummary);
appRoutes.post('/uniqueplayersjoined',contestReports.uniquePlayersJoined);
appRoutes.post('/cashflowsummary',contestReports.cashFlowSummary);
appRoutes.post('/hourly',contestReports.hourlyReport);
appRoutes.post('/retentionreport',contestReports.retentionReport);
appRoutes.post('/channelretentionreport',contestReports.channelRetentionReport);
appRoutes.post('/sourceretentionreport',contestReports.sourceRetentionReport);
appRoutes.get('/getallsource',contestReports.getAllSource);
appRoutes.post('/balancereport',contestReports.balanceReport);
appRoutes.get('/totalbalancereport',contestReports.totalBalancereport);
module.exports = appRoutes;